### ISSUE TITLE
"medy upgrade" broke my cygwin installation

### ISSUE THREAD

**Issue by WyntrHeart** [nobuyo/medy#16]
medy attempted to update Cygwin, and in doing so removed Cygwin files (cygwin1.dll) and was unable to continue the update. I was able to fix it with the normal setup program, but I thought you should know about this bug

**Comment by nobuyo** [comment]
Thank you for your report and apologize for any inconvenience. This project has not been maintained for a long time and I'll archive it. Sorry.
